#!/bin/bash

set -eux

GO111MODULE=on GOOS=linux GOARCH=amd64 go build -a -tags netgo -installsuffix netgo -o isuumo

# for n in `seq 3`
# TODO: deploy to all
for n in `seq 1`
do
	ssh isucon-server-${n} "sudo systemctl stop isuumo.go.service"
	ssh isucon-server-${n} "sudo systemctl stop nginx"
	scp isuumo isucon-server-${n}:/home/isucon/isuumo/webapp/go/isuumo
	ssh isucon-server-${n} "sudo systemctl start isuumo.go.service"
	# ssh isucon-server-${n} ":> /home/isucon/isutrain/webapp/go/script/logrotate; true"
	ssh isucon-server-${n} "sudo systemctl start nginx"
done
